#!/usr/bin/env node

/**
 * ⚙️ Fakelit.com Cloudways Configuration
 * Complete setup and configuration for fakelit.com deployment
 */

const fs = require('fs');
const path = require('path');

console.log('⚙️ Fakelit.com Cloudways Configuration');
console.log('=====================================\n');

// Configuration
const CLOUDWAYS_DOMAIN = 'fakelit.com';
const DEPLOYMENT_DIR = path.join(__dirname, 'fakelit-deployment');

console.log('📋 Configuration Checklist:');
console.log('===========================\n');

// Step 1: Environment Variables Configuration
console.log('✅ Step 1: Environment Variables Setup');
console.log('=====================================');
console.log('These variables need to be set in your Cloudways dashboard:');
console.log('');

const envVariables = {
    'NODE_ENV': 'production',
    'PORT': '3000',
    'OPENAI_API_KEY': 'your_openai_api_key_here',
    'SUPABASE_URL': 'your_supabase_project_url',
    'SUPABASE_ANON_KEY': 'your_supabase_anon_key',
    'SUPABASE_SERVICE_ROLE_KEY': 'your_supabase_service_role_key',
    'CLOUDWAYS_API_KEY': 'your_cloudways_api_key',
    'CLOUDWAYS_API_SECRET': 'your_cloudways_api_secret',
    'ENOM_USERNAME': 'your_enom_username',
    'ENOM_PASSWORD': 'your_enom_password'
};

Object.entries(envVariables).forEach(([key, value]) => {
    console.log(`   ${key}=${value}`);
});

console.log('\n📝 **How to set these in Cloudways:**');
console.log('1. Log in to Cloudways dashboard');
console.log('2. Go to your fakelit.com application');
console.log('3. Click "Application Settings"');
console.log('4. Click "Environment Variables"');
console.log('5. Add each variable above');

// Step 2: Cloudways Application Settings
console.log('\n✅ Step 2: Cloudways Application Settings');
console.log('=========================================');

console.log('🔧 **Application Configuration:**');
console.log('   • Application Name: fakelit-app');
console.log('   • PHP Version: 8.1 (or latest)');
console.log('   • Server: Your Cloudways server');
console.log('   • Project: Your Cloudways project');

console.log('\n🌐 **Domain Configuration:**');
console.log(`   • Primary Domain: ${CLOUDWAYS_DOMAIN}`);
console.log('   • SSL Certificate: Auto-generated by Cloudways');
console.log('   • Force HTTPS: Enabled');

console.log('\n📁 **File Structure:**');
console.log('   • Application Path: /home/master/applications/[app-name]/');
console.log('   • Public Directory: public_html/');
console.log('   • Node.js Application: Yes');

// Step 3: Node.js Configuration
console.log('\n✅ Step 3: Node.js Configuration');
console.log('===============================');

console.log('📦 **Package Configuration:**');
console.log('   • Node Version: 18.x or higher');
console.log('   • Start Script: node server.js');
console.log('   • Build Script: npm install');

console.log('\n🔧 **Dependencies Required:**');
const dependencies = [
    'express@^4.18.2',
    'cors@^2.8.5',
    'helmet@^7.0.0',
    'compression@^1.7.4',
    'express-rate-limit@^6.10.0',
    'dotenv@^16.3.1',
    'axios@^1.5.0',
    'uuid@^9.0.0'
];

dependencies.forEach(dep => {
    console.log(`   • ${dep}`);
});

// Step 4: File Upload Configuration
console.log('\n✅ Step 4: File Upload Configuration');
console.log('===================================');

console.log('📁 **Required Files to Upload:**');
const requiredFiles = [
    'package.json',
    'server.js',
    '.env',
    'public/index.html',
    'public/styles/',
    'public/js/',
    'public/images/',
    'routes/',
    'services/',
    'config/',
    'middleware/',
    'models/'
];

requiredFiles.forEach(file => {
    console.log(`   • ${file}`);
});

console.log('\n📤 **Upload Method:**');
console.log('   • Use SFTP client (FileZilla, Cyberduck)');
console.log('   • Connect to your Cloudways server');
console.log('   • Upload to: public_html/ directory');
console.log('   • Maintain folder structure');

// Step 5: Database Configuration
console.log('\n✅ Step 5: Database Configuration');
console.log('=================================');

console.log('🗄️ **Supabase Setup:**');
console.log('   • Create Supabase project at: https://supabase.com');
console.log('   • Get project URL and API keys');
console.log('   • Set environment variables');
console.log('   • Database will auto-initialize');

console.log('\n📊 **Database Tables:**');
console.log('   • users - User accounts and profiles');
console.log('   • conversations - Chat history');
console.log('   • counselors - AI counselor profiles');
console.log('   • analytics - Usage statistics');

// Step 6: API Configuration
console.log('\n✅ Step 6: API Configuration');
console.log('============================');

console.log('🔑 **OpenAI Configuration:**');
console.log('   • Get API key from: https://platform.openai.com');
console.log('   • Set OPENAI_API_KEY environment variable');
console.log('   • Model: gpt-3.5-turbo (default)');

console.log('\n🌐 **External APIs:**');
console.log('   • Cloudways API - Domain management');
console.log('   • Enom API - Domain registration');
console.log('   • Supabase - Database and auth');

// Step 7: Security Configuration
console.log('\n✅ Step 7: Security Configuration');
console.log('=================================');

console.log('🔒 **Security Headers:**');
console.log('   • Helmet.js - Security middleware');
console.log('   • CORS - Cross-origin requests');
console.log('   • Rate limiting - API protection');
console.log('   • SSL/HTTPS - Auto-configured by Cloudways');

console.log('\n🛡️ **Content Security Policy:**');
console.log('   • Script sources: self, OpenAI, Supabase');
console.log('   • Style sources: self, Google Fonts');
console.log('   • Image sources: self, data, https');
console.log('   • Frame sources: Ready Player Me');

// Step 8: Performance Configuration
console.log('\n✅ Step 8: Performance Configuration');
console.log('====================================');

console.log('⚡ **Optimization Settings:**');
console.log('   • Compression - Gzip enabled');
console.log('   • Static file serving - Optimized');
console.log('   • Caching - Browser and server');
console.log('   • CDN - Cloudways CDN available');

console.log('\n📱 **Mobile Optimization:**');
console.log('   • Responsive design - Mobile-first');
console.log('   • Touch-friendly interface');
console.log('   • Fast loading times');
console.log('   • Progressive Web App ready');

// Step 9: Monitoring Configuration
console.log('\n✅ Step 9: Monitoring Configuration');
console.log('===================================');

console.log('📊 **Health Checks:**');
console.log(`   • Main: https://${CLOUDWAYS_DOMAIN}/health`);
console.log(`   • API: https://${CLOUDWAYS_DOMAIN}/api/fakelit-chatbot/status`);
console.log('   • Database: Auto-monitored');
console.log('   • Performance: Cloudways monitoring');

console.log('\n🔍 **Logging:**');
console.log('   • Application logs - Cloudways dashboard');
console.log('   • Error tracking - Built-in');
console.log('   • Performance metrics - Available');
console.log('   • User analytics - Optional');

// Step 10: Deployment Commands
console.log('\n✅ Step 10: Deployment Commands');
console.log('==============================');

console.log('🚀 **SSH Commands for Cloudways:**');
console.log('```bash');
console.log('# Navigate to application directory');
console.log('cd /home/master/applications/[your-app-name]/public_html/');
console.log('');
console.log('# Install dependencies');
console.log('npm install');
console.log('');
console.log('# Install additional dependencies');
console.log('npm install express-rate-limit');
console.log('');
console.log('# Check Node.js version');
console.log('node --version');
console.log('');
console.log('# Test the application');
console.log('npm start');
console.log('');
console.log('# Restart application (if needed)');
console.log('sudo systemctl restart [your-app-name]');
console.log('```');

// Step 11: Testing Configuration
console.log('\n✅ Step 11: Testing Configuration');
console.log('=================================');

console.log('🧪 **Test URLs:**');
console.log(`   • Main Page: https://${CLOUDWAYS_DOMAIN}/`);
console.log(`   • Health Check: https://${CLOUDWAYS_DOMAIN}/health`);
console.log(`   • Chatbot API: https://${CLOUDWAYS_DOMAIN}/api/fakelit-chatbot/status`);
console.log(`   • Chatbot Test: https://${CLOUDWAYS_DOMAIN}/fakelit-chatbot.html`);

console.log('\n✅ **Expected Results:**');
console.log('   • Main page loads with Fakelit.com branding');
console.log('   • AI chatbot appears on the right side');
console.log('   • Chatbot responds to questions');
console.log('   • All API endpoints return 200 status');
console.log('   • SSL certificate is valid');

// Step 12: Troubleshooting
console.log('\n✅ Step 12: Troubleshooting Guide');
console.log('==================================');

console.log('🔧 **Common Issues:**');
console.log('   • "Upgrade now" message: Files not uploaded');
console.log('   • 500 errors: Check environment variables');
console.log('   • Chatbot not working: Verify OpenAI API key');
console.log('   • Database errors: Check Supabase configuration');
console.log('   • Port issues: Cloudways handles automatically');

console.log('\n📞 **Support Resources:**');
console.log('   • Cloudways Support: https://support.cloudways.com');
console.log('   • Application Logs: Cloudways dashboard');
console.log('   • SSH Access: Available in dashboard');
console.log('   • Documentation: Check project README');

console.log('\n🎉 **Configuration Complete!**');
console.log('=============================');
console.log(`Your Fakelit.com application is now configured for Cloudways deployment.`);
console.log(`Follow the steps above to deploy and test your application.`);

console.log('\n📋 **Next Steps:**');
console.log('=================');
console.log('1. Set environment variables in Cloudways');
console.log('2. Upload all files to public_html/');
console.log('3. Install dependencies via SSH');
console.log('4. Restart the application');
console.log('5. Test all functionality');
console.log('6. Monitor performance and logs');

console.log('\n✨ **Fakelit.com is ready for production!** ✨'); 